/**
 * @file parser.test.ts
 * @description 记忆文档解析与序列化测试
 */
import { describe, expect, it } from 'vitest';
import { createEmptyMemoryDoc, parseMemoryDoc, serializeMemoryDoc } from '@/ai/memory/parser';

const VALID_MEMORY_MD = `# User Memory

> Auto-generated by Tibis. This file stores user preferences and habits learned from conversations.
> You can edit this file directly. Changes will take effect in the next conversation.

## Instructions
- 始终使用 TypeScript
- 代码注释使用中文

## Preferences
- 偏好函数式编程风格

## Habits
- 习惯先写测试再写实现

## Facts
- 项目使用 Vue 3 + Pinia

## Projects
- tibis: 本地优先的 AI 编辑器

## Current Context
- 正在开发记忆系统功能
`;

describe('parseMemoryDoc', () => {
  it('parses a valid MEMORY.md into MemoryDoc', () => {
    const doc = parseMemoryDoc(VALID_MEMORY_MD);

    expect(doc.sections).toHaveLength(6);

    const instructions = doc.sections.find((s) => s.category === 'Instructions');
    expect(instructions?.items).toHaveLength(2);
    expect(instructions?.items[0].content).toBe('始终使用 TypeScript');
    expect(instructions?.items[1].content).toBe('代码注释使用中文');

    const preferences = doc.sections.find((s) => s.category === 'Preferences');
    expect(preferences?.items).toHaveLength(1);
    expect(preferences?.items[0].content).toBe('偏好函数式编程风格');

    const habits = doc.sections.find((s) => s.category === 'Habits');
    expect(habits?.items).toHaveLength(1);

    const facts = doc.sections.find((s) => s.category === 'Facts');
    expect(facts?.items).toHaveLength(1);

    const projects = doc.sections.find((s) => s.category === 'Projects');
    expect(projects?.items).toHaveLength(1);

    const currentContext = doc.sections.find((s) => s.category === 'Current Context');
    expect(currentContext?.items).toHaveLength(1);
  });

  it('handles empty sections gracefully', () => {
    const text = `## Instructions
- 规则一

## Preferences

## Habits
- 习惯一
`;
    const doc = parseMemoryDoc(text);

    expect(doc.sections.find((s) => s.category === 'Instructions')?.items).toHaveLength(1);
    expect(doc.sections.find((s) => s.category === 'Preferences')?.items).toHaveLength(0);
    expect(doc.sections.find((s) => s.category === 'Habits')?.items).toHaveLength(1);
  });

  it('returns empty items for missing sections', () => {
    const text = '## Instructions\n- 规则一\n';
    const doc = parseMemoryDoc(text);

    expect(doc.sections).toHaveLength(6);
    expect(doc.sections.find((s) => s.category === 'Instructions')?.items).toHaveLength(1);
    expect(doc.sections.find((s) => s.category === 'Preferences')?.items).toHaveLength(0);
  });

  it('handles completely empty input', () => {
    const doc = parseMemoryDoc('');

    expect(doc.sections).toHaveLength(6);
    for (const section of doc.sections) {
      expect(section.items).toHaveLength(0);
    }
  });

  it('stops extracting at the next h2 heading', () => {
    const text = `## Instructions
- 规则一
- 规则二
## Preferences
- 偏好一
`;
    const doc = parseMemoryDoc(text);

    const instructions = doc.sections.find((s) => s.category === 'Instructions');
    expect(instructions?.items).toHaveLength(2);

    const preferences = doc.sections.find((s) => s.category === 'Preferences');
    expect(preferences?.items).toHaveLength(1);
  });

  it('ignores empty bullet points', () => {
    const text = `## Instructions
-
- 规则一
-   `;
    const doc = parseMemoryDoc(text);

    const instructions = doc.sections.find((s) => s.category === 'Instructions');
    expect(instructions?.items).toHaveLength(1);
    expect(instructions?.items[0].content).toBe('规则一');
  });
});

describe('serializeMemoryDoc', () => {
  it('serializes a MemoryDoc to Markdown', () => {
    const doc = createEmptyMemoryDoc();
    const instructions = doc.sections.find((s) => s.category === 'Instructions')!;
    instructions.items.push({ content: '规则一' }, { content: '规则二' });

    const text = serializeMemoryDoc(doc);

    expect(text).toContain('## Instructions');
    expect(text).toContain('- 规则一');
    expect(text).toContain('- 规则二');
  });

  it('skips empty sections', () => {
    const doc = createEmptyMemoryDoc();
    const instructions = doc.sections.find((s) => s.category === 'Instructions')!;
    instructions.items.push({ content: '规则一' });

    const text = serializeMemoryDoc(doc);

    expect(text).toContain('## Instructions');
    expect(text).not.toContain('## Preferences');
    expect(text).not.toContain('## Habits');
  });

  it('round-trips: serialize → parse produces equivalent doc', () => {
    const original = createEmptyMemoryDoc();
    original.sections.find((s) => s.category === 'Instructions')!.items.push({ content: '规则一' });
    original.sections.find((s) => s.category === 'Facts')!.items.push({ content: '事实一' });

    const serialized = serializeMemoryDoc(original);
    const parsed = parseMemoryDoc(serialized);

    for (const category of ['Instructions', 'Facts'] as const) {
      const origSection = original.sections.find((s) => s.category === category)!;
      const parsedSection = parsed.sections.find((s) => s.category === category)!;
      expect(parsedSection.items.map((i) => i.content)).toEqual(origSection.items.map((i) => i.content));
    }
  });
});

describe('createEmptyMemoryDoc', () => {
  it('creates a doc with all 6 categories and no items', () => {
    const doc = createEmptyMemoryDoc();

    expect(doc.sections).toHaveLength(6);
    expect(doc.sections.map((s) => s.category)).toEqual(['Instructions', 'Preferences', 'Habits', 'Facts', 'Projects', 'Current Context']);
    for (const section of doc.sections) {
      expect(section.items).toHaveLength(0);
    }
  });
});
